framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            'assets/': ''
            '%kernel.project_dir%/var/build/translations': 'var/build/translations'

        excluded_patterns:
            - '*/assets/styles/_*.scss'
            - '*/assets/styles/**/_*.scss'
            - '*/assets/icons/**'
        importmap_polyfill: false

react:
    controllers_path: '%kernel.project_dir%/assets/build/react/controllers'

svelte:
    controllers_path: '%kernel.project_dir%/assets/build/svelte/controllers'
