ux_icons:
    default_icon_attributes:
        class: 'Icon'

    icon_sets:
        
        lu: # Lucide icons
            alias: 'lucide'

        # FeatureBox icons
        feature:
            alias: 'lucide'
            # icon_attributes:
