workers:
    docker_compose: ~
    sass:
        cmd: ['symfony', 'console', 'sass:build', '--watch']

http:
    use_gzip: true # Gzip compresses your HTTP responses to reduce the size of the data that's sent to your users. This can help improve the performance of your site.
