name: Symfony UX Turbo

on:
    push:
    pull_request:

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: zip

            - uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Turbo

            - name: Install PHPUnit dependencies
              working-directory: src/Turbo
              run: vendor/bin/simple-phpunit --version

            - name: PHPStan
              working-directory: src/Turbo
              run: vendor/bin/phpstan analyse --no-progress

    tests:
        runs-on: ubuntu-latest
        strategy:
           fail-fast: false
           matrix:
               php-version: ['8.1']
               dependency-version: ['lowest', 'highest']

        services:
            mercure:
                image: dunglas/mercure
                env:
                    SERVER_NAME: :3000
                    MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
                    MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
                    MERCURE_EXTRA_DIRECTIVES: |
                        anonymous
                        cors_origins *
                ports:
                    - 3000:3000

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Install Turbo packages
              uses: ramsey/composer-install@v2
              with:
                working-directory: src/Turbo
                dependency-versions: ${{ matrix.dependency-version }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v3
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install JavaScript dependencies
              working-directory: src/Turbo/tests/app
              run: yarn install

            - name: Build JavaScript
              working-directory: src/Turbo/tests/app
              run: yarn build

            - name: Create DB
              working-directory: src/Turbo/tests/app
              run: php public/index.php doctrine:schema:create

            - name: Run tests
              working-directory: src/Turbo
              run: vendor/bin/simple-phpunit
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[self]=1'
